apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-external-secrets
  namespace: infisical
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: infisical
      app.kubernetes.io/instance: infisical
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: external-secrets
    ports:
    - protocol: TCP
      port: 8080
