apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-allow-dns-egress.yaml
  - 01-allow-intra-namespace.yaml
  - 02-allow-ingress-from-external-secrets.yaml
  - 03-allow-ingress-external.yaml
  - 99-default-deny-all.yaml
