apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Network policies for kube-system
  - 00-allow-dns-ingress.yaml
  - 01-default-deny-all.yaml
  - 02-allow-dns-egress.yaml
  - 03-allow-intra-namespace.yaml
  - 04-allow-api-egress.yaml
