apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Databases and persistent data stores
  sourceRepos:
    - https://github.com/holdennguyen/homelab.git
  destinations: []
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
