apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: identity
    app.kubernetes.io/managed-by: argocd
spec:
  project: apps
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.12.4
    helm:
      valuesObject:
        authentik:
          existingSecret:
            secretName: authentik-secret

        blueprints:
          configMaps:
            - authentik-blueprints

        global:
          envFrom:
            - secretRef:
                name: authentik-secret
          env:
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: authentik-postgresql
            - name: AUTHENTIK_POSTGRESQL__PORT
              value: "5432"
            - name: AUTHENTIK_POSTGRESQL__USER
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik
          affinity:
            podAntiAffinity: none
            nodeAffinity:
              type: none

        server:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
          replicas: 1
          service:
            type: NodePort
            nodePortHttp: 30500
            nodePortHttps: 30501

        worker:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
          replicas: 1

        postgresql:
          enabled: true
          auth:
            username: authentik
            database: authentik
            existingSecret: authentik-secret
            secretKeys:
              adminPasswordKey: pg-password
              userPasswordKey: pg-password
          primary:
            persistence:
              enabled: true
              size: 2Gi
            containerSecurityContext:
              readOnlyRootFilesystem: false
            resourcesPreset: "none"
          readReplicas:
            resourcesPreset: "none"
          backup:
            resourcesPreset: "none"
          passwordUpdateJob:
            resourcesPreset: "none"
          volumePermissions:
            resourcesPreset: "none"
          metrics:
            resourcesPreset: "none"

        serviceAccount:
          create: false

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
