apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: secrets
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "0.20.4"
    helm:
      valuesObject:
        replicaCount: 1
        installCRDs: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
        controller:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
