apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: productivity
    app.kubernetes.io/managed-by: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/holdennguyen/homelab.git
    targetRevision: HEAD
    path: k8s/apps/vikunja
  destination:
    server: https://kubernetes.default.svc
    namespace: vikunja
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
