apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-db-secret
  namespace: vikunja
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: vikunja-db-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: VIKUNJA_POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: VIKUNJA_POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: VIKUNJA_POSTGRES_DB
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: VIKUNJA_OIDC_CLIENT_SECRET
