apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vikunja

resources:
  - external-secret.yaml
  - postgresql-pvc.yaml
  - postgresql-service.yaml
  - postgresql-hba-config.yaml
  - postgresql-deployment.yaml
  - vikunja-config.yaml
  - vikunja-pvc.yaml
  - vikunja-service.yaml
  - vikunja-deployment.yaml
  - vikunja-servicemonitor.yaml
