apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  # Network policies
  - 00-default-deny-all.yaml
  - 01-allow-dns-egress.yaml
  - 02-allow-intra-namespace.yaml
  - 03-allow-ingress-grafana.yaml
  - 04-allow-egress-api.yaml
