apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-allow-dns-egress.yaml
  - 01-allow-intra-namespace.yaml
  - 02-allow-egress-api.yaml
  - 03-allow-egress-https.yaml
  - 99-default-deny-all.yaml
